// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsgmIwQ2F_CnE1ncWjqgPkU6z5wB9BsS4',
    appId: '1:991765269846:web:f6b750a5a774eed4cadaf7',
    messagingSenderId: '991765269846',
    projectId: 'planarity-xyz',
    authDomain: 'planarity-xyz.firebaseapp.com',
    storageBucket: 'planarity-xyz.firebasestorage.app',
    measurementId: 'G-Q2934PF6DM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp04A4BBhV3d3gceYQhIpcjxwqPlzZGTY',
    appId: '1:991765269846:ios:8d26bdf3ed3bdaf1cadaf7',
    messagingSenderId: '991765269846',
    projectId: 'planarity-xyz',
    storageBucket: 'planarity-xyz.firebasestorage.app',
    iosClientId: '991765269846-6u5n56v48erd5vu6t9berg38ie774kb4.apps.googleusercontent.com',
    iosBundleId: 'dev.wxlfe.planarity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp04A4BBhV3d3gceYQhIpcjxwqPlzZGTY',
    appId: '1:991765269846:ios:8d26bdf3ed3bdaf1cadaf7',
    messagingSenderId: '991765269846',
    projectId: 'planarity-xyz',
    storageBucket: 'planarity-xyz.firebasestorage.app',
    iosClientId: '991765269846-6u5n56v48erd5vu6t9berg38ie774kb4.apps.googleusercontent.com',
    iosBundleId: 'dev.wxlfe.planarity',
  );
}
